# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(939, 639)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_SignUp = QtWidgets.QPushButton(self.centralwidget)
        self.Button_SignUp.setGeometry(QtCore.QRect(710, 10, 93, 28))
        self.Button_SignUp.setObjectName("Button_SignUp")
        self.Button_SignIn = QtWidgets.QPushButton(self.centralwidget)
        self.Button_SignIn.setGeometry(QtCore.QRect(830, 10, 93, 28))
        self.Button_SignIn.setObjectName("Button_SignIn")
        self.Box_Gold = QtWidgets.QCheckBox(self.centralwidget)
        self.Box_Gold.setGeometry(QtCore.QRect(760, 130, 121, 19))
        self.Box_Gold.setObjectName("Box_Gold")
        self.Box_COVID = QtWidgets.QCheckBox(self.centralwidget)
        self.Box_COVID.setGeometry(QtCore.QRect(760, 160, 151, 19))
        self.Box_COVID.setObjectName("Box_COVID")
        self.Box_Weather = QtWidgets.QCheckBox(self.centralwidget)
        self.Box_Weather.setGeometry(QtCore.QRect(760, 230, 91, 19))
        self.Box_Weather.setObjectName("Box_Weather")
        self.Box_News = QtWidgets.QCheckBox(self.centralwidget)
        self.Box_News.setGeometry(QtCore.QRect(760, 300, 91, 19))
        self.Box_News.setObjectName("Box_News")
        self.Box_Oil = QtWidgets.QCheckBox(self.centralwidget)
        self.Box_Oil.setGeometry(QtCore.QRect(760, 330, 91, 19))
        self.Box_Oil.setObjectName("Box_Oil")
        self.Box_Prattle = QtWidgets.QCheckBox(self.centralwidget)
        self.Box_Prattle.setGeometry(QtCore.QRect(760, 360, 91, 19))
        self.Box_Prattle.setObjectName("Box_Prattle")
        self.AnswerArea = QtWidgets.QScrollArea(self.centralwidget)
        self.AnswerArea.setGeometry(QtCore.QRect(50, 40, 631, 531))
        self.AnswerArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.AnswerArea.setWidgetResizable(True)
        self.AnswerArea.setObjectName("AnswerArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 629, 529))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Text_Data = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.Text_Data.setGeometry(QtCore.QRect(0, 0, 631, 531))
        self.Text_Data.setObjectName("Text_Data")
        self.AnswerArea.setWidget(self.scrollAreaWidgetContents)
        self.Button_Update = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Update.setGeometry(QtCore.QRect(770, 420, 93, 28))
        self.Button_Update.setObjectName("Button_Update")
        self.Text_Weather = QtWidgets.QTextEdit(self.centralwidget)
        self.Text_Weather.setGeometry(QtCore.QRect(780, 260, 104, 31))
        self.Text_Weather.setObjectName("Text_Weather")
        self.Text_COVID19 = QtWidgets.QTextEdit(self.centralwidget)
        self.Text_COVID19.setGeometry(QtCore.QRect(780, 190, 104, 31))
        self.Text_COVID19.setObjectName("Text_COVID19")
        self.Button_SignOut = QtWidgets.QPushButton(self.centralwidget)
        self.Button_SignOut.setGeometry(QtCore.QRect(830, 50, 93, 28))
        self.Button_SignOut.setObjectName("Button_SignOut")
        self.Label_UID = QtWidgets.QLabel(self.centralwidget)
        self.Label_UID.setGeometry(QtCore.QRect(710, 50, 101, 31))
        self.Label_UID.setText("")
        self.Label_UID.setObjectName("Label_UID")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 939, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "订阅式消息中心"))
        self.Button_SignUp.setText(_translate("MainWindow", "登录"))
        self.Button_SignIn.setText(_translate("MainWindow", "注册"))
        self.Box_Gold.setText(_translate("MainWindow", "黄金实时价格"))
        self.Box_COVID.setText(_translate("MainWindow", "新冠疫情实时数据"))
        self.Box_Weather.setText(_translate("MainWindow", "天气"))
        self.Box_News.setText(_translate("MainWindow", "今日头条"))
        self.Box_Oil.setText(_translate("MainWindow", "实时油价"))
        self.Box_Prattle.setText(_translate("MainWindow", "土味情话"))
        self.Button_Update.setText(_translate("MainWindow", "更新"))
        self.Button_SignOut.setText(_translate("MainWindow", "退出"))
