# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(448, 343)
        self.Button_SignUp = QtWidgets.QPushButton(Dialog)
        self.Button_SignUp.setGeometry(QtCore.QRect(180, 240, 93, 28))
        self.Button_SignUp.setObjectName("Button_SignUp")
        self.Label_Tip = QtWidgets.QLabel(Dialog)
        self.Label_Tip.setGeometry(QtCore.QRect(100, 185, 261, 21))
        self.Label_Tip.setText("")
        self.Label_Tip.setObjectName("Label_Tip")
        self.Lable_Account = QtWidgets.QLabel(Dialog)
        self.Lable_Account.setGeometry(QtCore.QRect(90, 90, 72, 15))
        self.Lable_Account.setObjectName("Lable_Account")
        self.Lable_Password = QtWidgets.QLabel(Dialog)
        self.Lable_Password.setGeometry(QtCore.QRect(90, 140, 72, 15))
        self.Lable_Password.setObjectName("Lable_Password")
        self.Text_Account = QtWidgets.QTextEdit(Dialog)
        self.Text_Account.setGeometry(QtCore.QRect(150, 80, 191, 31))
        self.Text_Account.setObjectName("Text_Account")
        self.Text_Password = QtWidgets.QTextEdit(Dialog)
        self.Text_Password.setGeometry(QtCore.QRect(150, 130, 191, 31))
        self.Text_Password.setObjectName("Text_Password")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "登录"))
        self.Button_SignUp.setText(_translate("Dialog", "登录"))
        self.Lable_Account.setText(_translate("Dialog", "账号："))
        self.Lable_Password.setText(_translate("Dialog", "密码："))
