# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Tips.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tips(object):
    def setupUi(self, Tips):
        Tips.setObjectName("Tips")
        Tips.resize(362, 129)
        self.label = QtWidgets.QLabel(Tips)
        self.label.setGeometry(QtCore.QRect(40, 20, 311, 81))
        self.label.setObjectName("label")

        self.retranslateUi(Tips)
        QtCore.QMetaObject.connectSlotsByName(Tips)

    def retranslateUi(self, Tips):
        _translate = QtCore.QCoreApplication.translate
        Tips.setWindowTitle(_translate("Tips", "提示框"))
        self.label.setText(_translate("Tips", "请登录 / 注册后再使用本应用！谢谢支持！"))
